import fs from "node:fs";
import path from "node:path";
import type { RunResult } from "./runner.js";

/**
 * Renders a RunResult as a clean markdown report and writes it to disk.
 * Kept separate from runner.ts so the formatting logic can be iterated
 * on independently of the live-render/concurrency logic.
 */
export function writeReport(
  result: RunResult,
  outputPath: string,
  repoLabel: string,
): void {
  const lines: string[] = [];

  lines.push(`# critcache report — ${repoLabel}`);
  lines.push("");
  lines.push(`Generated ${new Date().toISOString()}`);
  lines.push("");

  // ---------------------------------------------------------------------------
  // Savings summary table
  // ---------------------------------------------------------------------------
  lines.push("## Savings summary");
  lines.push("");
  lines.push("| Metric | Value |");
  lines.push("| --- | --- |");
  lines.push(`| Files analyzed | ${result.rows.length} |`);
  lines.push(`| Cache hits | ${result.cacheHits} |`);
  lines.push(`| Cache misses | ${result.cacheMisses} |`);
  lines.push(`| Benchmark cost (no caching) | $${result.totalBenchmarkCostUsd.toFixed(4)} |`);
  lines.push(`| Actual charge (via BTL) | $${result.totalChargeUsd.toFixed(4)} |`);
  lines.push(`| **Total saved** | **$${result.totalSavedUsd.toFixed(4)}** |`);

  if (result.totalBenchmarkCostUsd > 0) {
    const pct = (result.totalSavedUsd / result.totalBenchmarkCostUsd) * 100;
    lines.push(`| Savings rate | ${pct.toFixed(1)}% |`);
  }
  lines.push("");

  // ---------------------------------------------------------------------------
  // Repo-level synthesis
  // ---------------------------------------------------------------------------
  lines.push("## Repo-level findings");
  lines.push("");

  if (result.synthesis) {
    lines.push("### Architecture overview");
    lines.push("");
    lines.push(result.synthesis.architecture_overview);
    lines.push("");

    lines.push("### Top risks");
    lines.push("");
    if (result.synthesis.top_risks.length === 0) {
      lines.push("_None flagged._");
    } else {
      for (const risk of result.synthesis.top_risks) {
        lines.push(`- ${risk}`);
      }
    }
    lines.push("");

    lines.push("### Suggested next steps");
    lines.push("");
    if (result.synthesis.next_steps.length === 0) {
      lines.push("_None suggested._");
    } else {
      for (const step of result.synthesis.next_steps) {
        lines.push(`- ${step}`);
      }
    }
    lines.push("");
  } else {
    lines.push(
      `_Synthesis unavailable: ${result.synthesisError ?? "unknown reason"}_`,
    );
    lines.push("");
  }

  // ---------------------------------------------------------------------------
  // Per-file detail
  // ---------------------------------------------------------------------------
  lines.push("## Per-file analysis");
  lines.push("");

  for (const row of result.rows) {
    lines.push(`### \`${row.file.relPath}\``);
    lines.push("");

    if (row.status === "error") {
      const msg = row.result?.requestError ?? row.result?.parseError ?? "unknown error";
      lines.push(`⚠️ **Error:** ${msg}`);
      lines.push("");
      continue;
    }

    const analysis = row.result?.analysis;
    const usage    = row.result?.usage;

    if (analysis) {
      lines.push(`- **Role:** ${analysis.role}`);
      lines.push(`- **Complexity:** ${analysis.complexity}`);
      lines.push(`- **Test gaps:** ${analysis.test_gaps}`);
      lines.push(`- **Security note:** ${analysis.security_note}`);
      lines.push(`- **Summary:** ${analysis.summary}`);
    }

    if (usage) {
      const tier  = usage.cacheTier ?? "unknown";
      const saved = usage.savedUsd !== undefined ? `$${usage.savedUsd.toFixed(4)}` : "n/a";
      lines.push(`- **Cache tier:** ${tier} · **Saved:** ${saved}`);
    }

    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("_Generated by [critcache](https://github.com/) — powered by BTL Runtime._");
  lines.push("");

  const fullOutputPath = path.resolve(outputPath);
  fs.writeFileSync(fullOutputPath, lines.join("\n"), "utf-8");
}
